### ISSUE TITLE
The flashing lights cutscene mid Soul Master fight is not skipped in Godhome

### ISSUE THREAD

**Issue by JoannaFalkowska** [fifty-six/HollowKnight.QoL#31]
With all `SkipCutscenes` settings turned on, the flashing lights nightmare "cutscene" is not being skipped in Godhome fights (both in the Pantheon and when done as a single fight).

Other people told me that this works in the Soul Sanctum fight during a normal run, but I haven't tested that.

It would be great to add this skip to the Godhome fights as well, it's a huge deal for people with photosensitivity 🙏🏻

**Comment by fifty-six** [comment]
I'll look into this when I get the chance, busyish with exams and such atm

**Comment by fifty-six** [comment]
https://user-images.githubusercontent.com/10470872/169647714-712194ef-1f52-416e-8f05-06bf1a1ff73a.mp4

**Comment by JoannaFalkowska** [comment]
Thank you so much for this, it makes all the difference in the world! ❤️ 🎉

**Comment by JoannaFalkowska** [comment]
Hmm, so after updating to the current version with Scarab, this fix didn't work for me in the P2 fight - the cutscene happened like it normally would.

This was my mod setup in that first test:
![image](https://user-images.githubusercontent.com/14551750/169658026-1ece1c5b-7fa0-4a57-be98-0d72af469626.png)
![image](https://user-images.githubusercontent.com/14551750/169658044-85715d93-89c1-480c-8944-b74ed2687b1a.png)
![image](https://user-images.githubusercontent.com/14551750/169658057-0648b3bc-5cf3-4372-b9b1-ee10e0c758d0.png)

Then I disabled everything else, which didn't help:
![image](https://user-images.githubusercontent.com/14551750/169658414-9da1d828-ef54-408b-9818-adf92b6870dc.png)

Finally I also uninstalled everything and reinstalled ModdingAPI and QoL, which didn't help either.

---

I noticed that QoL is now disabled (turned off in Mods menu) every time after reopening the game, even though it's set to `true` in `ModEnabledSettings`. Confusing. 

After turning it on in the game main manu and loading up my save QoL seems to be working fine - Salubra stays properly killed. Just this damn cutscene doesn't want to go.

I tested in P2 and in Soul Master single fight, I also tried to test Soul Tyrant but tbh after all this I just died a couple times and gave up lol.

My logs & configs from my last attempt:
```
[INFO]:[API] - Starting mod loading
[INFO]:[API] - Loading Global Settings
[INFO]:[API] - Deleting modlogs older than 7 days ago
[INFO]:[QoL] - Initializing
[INFO]:[QoL] - Loading Global Settings
[INFO]:[API] - Creating mod preloads
[INFO]:[API] - Finished loading mods:
[INFO]:[API] - Modding API: 1.5.78.11833-71
[INFO]:[API] - QoL : 4.4.0.0-7cea2c
[INFO]:[API] - 
[INFO]:[API] - Preloaded reflection in 1635ms
```
```
{
  "ModEnabledSettings": {
    "QoL": true
  },
  "LoggingLevel": 2,
  "ConsoleSettings": {
    "UseLogColors": false,
    "FineColor": "grey",
    "InfoColor": "white",
    "DebugColor": "white",
    "WarningColor": "yellow",
    "ErrorColor": "red",
    "DefaultColor": "white",
    "ToggleHotkey": "F10",
    "MaxMessageCount": 24,
    "Font": "",
    "FontSize": 12
  },
  "ShowDebugLogInGame": false,
  "PreloadBatchSize": 5,
  "ModlogMaxAge": 7
}
```

```
{
  "EnabledModules": {
    "Dev": true,
    "FasterLoads": true,
    "FastMenus": true,
    "FastText": false,
    "FixFireballs": true,
    "FixVolume": true,
    "InfinitePoP": false,
    "LockMenuCursor": false,
    "NPCSellAll": false,
    "OldDashmaster": false,
    "PatchedBosses": false,
    "SalubraKiller": true,
    "SaneUumuu": true,
    "SkipCutscenes": true,
    "SpeedBroke": false,
    "UnencryptedSaves": true
  },
  "Booleans": {
    "Dev:LogUnityErrors": true,
    "Dev:EnableStacktrace": true,
    "NPCSellAll:LemmSellAll": true,
    "NPCSellAll:JinnSellAll": true,
    "NPCSellAll:NailsmithBuyAll": true,
    "PatchedBosses:SporeShroomHollowKnight": true,
    "PatchedBosses:NoBackrolls": false,
    "PatchedBosses:SleepyCrystalGuardian": false,
    "SkipCutscenes:DreamersGet": true,
    "SkipCutscenes:AbsoluteRadiance": true,
    "SkipCutscenes:AbyssShriekGet": true,
    "SkipCutscenes:AfterKingsBrandGet": true,
    "SkipCutscenes:BlackEggOpen": true,
    "SkipCutscenes:StagArrive": true,
    "SkipCutscenes:HallOfGodsStatues": true,
    "SkipCutscenes:GodhomeEntry": true,
    "SkipCutscenes:PureVesselRoar": true,
    "SkipCutscenes:FirstTimeBosses": true,
    "SkipCutscenes:FirstCharm": true,
    "SkipCutscenes:AutoSkipCinematics": true,
    "SkipCutscenes:AllowSkippingNonskippable": true,
    "SkipCutscenes:SkipCutscenesWithoutPrompt": true,
    "SkipCutscenes:InstantSceneFadeIns": true,
    "SkipCutscenes:SoulMasterPhaseTransitionSkip": true,
    "SpeedBroke:MenuDrop": true,
    "SpeedBroke:Storage": true,
    "SpeedBroke:Superslides": true,
    "SpeedBroke:Televator": true,
    "SpeedBroke:ExplosionPogo": true,
    "SpeedBroke:GrubsThroughWalls": true,
    "SpeedBroke:LeverSkips": true,
    "SpeedBroke:NoHardFalls": false,
    "SpeedBroke:ShadeSoulLeverSkip": false,
    "SpeedBroke:CrystalisedMoundSpikes": true
  },
  "Floats": {
    "FixVolume:DoubleDamageVolumeModifier": 0.8
  },
  "Integers": {}
}
```

Let me know if I'm doing something wrong here, or if you need more info/logs/anything. Cheers!

**Comment by JoannaFalkowska** [comment]
Okay, reading through the code I figured out how to make it work - I think one little boolean slipped your attention in this line: https://github.com/fifty-six/HollowKnight.QoL/commit/4e6dd7ce5521e9a7338a7cfb4d4c1a425a50c638#diff-926bb904db95bb360576511415399e76f466e9b88fc566fbbb022bb2d7f39c87R181

When skip toggle is turned to `false`, then the cutscene is actually skipped.

I raised a PR, though I have no idea if this fix will work properly or not: https://github.com/fifty-six/HollowKnight.QoL/pull/34

**Comment by fifty-six** [comment]
Ah yeah that is backwards, that fix should be right

**Comment by JoannaFalkowska** [comment]
Woo, happy I could contribute 😄

**Comment by fifty-six** [comment]
Cool, the new version should be up now if you want to update and have the toggle be true like it should have been
