### ISSUE TITLE
Godseeker Soul Master fight doesn't continue to second phase

### ISSUE THREAD

**Issue by dfoxfranke** [fifty-six/HollowKnight.QoL#35]
In QoL 4.5, when fighting Soul Master in Godseeker mode, when the second phase of the fight ought to begin, Soul Master instead just floats off the edge of the screen and doesn't return. This happens whenever the QoL mod is installed, even if it's disabled from the in-game menu. This is a regression from 4.4 and so almost certainly related to https://github.com/fifty-six/HollowKnight.QoL/commit/4e6dd7ce5521e9a7338a7cfb4d4c1a425a50c638.

**Comment by fifty-six** [comment]
Thanks for the report!

**Comment by dfoxfranke** [comment]
Whatever you uploaded to Scarab this morning seems to contain this fix, as Soul Master now works, but doesn't match what's in git. The version shows up as expected as 4.6.0.0 in the Scarab UI, but in-game it shows up as 4.5.0.0-5c0b45.

**Comment by fifty-six** [comment]
Ah I forgot to rebuild after bumping the version, I'll just bump it again.
